version: "3.7"
services:
  model_predictor:
    build: 
      context: ../../
      dockerfile: ./docker/model_predictor/Dockerfile
    restart: on-failure
    volumes:
      - ../../data/raw_data:/solution/data/raw_data
      - ../../data/train_data:/solution/data/train_data
      - ../../data/model_config:/solution/data/model_config
      - ../../data/captured_data:/solution/data/captured_data
    ports:
      - ${PORT}:8000
    environment:
      MLFLOW_TRACKING_URI: http://host.docker.internal:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: /bin/sh -c "python src/model_predictor.py" --port 8000